spring:
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.139.180:8281/realms/saas-realm
          jwk-set-uri: http://172.20.139.180:8281/realms/saas-realm/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://172.20.139.180:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

keycloak:
  server-url: http://172.20.139.180:8281
  realm: saas-realm
  client-id: saas-client
  client-secret: is2bAtb95xjb7OZyxa6SqDwwRINy2XHo
  openIdConnectUrl: http://172.20.139.180:8281/realms/saas-realm/.well-known/openid-configuration
