spring:
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

host:
  ip: 172.20.139.180

keycloak:
  server-url: http://${host.ip}:8281
  realm: saas-realm
  client-id: saas-client
  client-secret: is2bAtb95xjb7OZyxa6SqDwwRINy2XHo
  openIdConnectUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/.well-known/openid-configuration

discovery:
  server-url: http://${host.ip}:8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${discovery.server-url}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
